stages:
  - sync

variables:
  GITHUB_REPO: "SlavMAK/obsidian-bitrix24"
  TARGET_BRANCH: "master" # Ветка в GitHub

sync_to_github: #Так как остаётся репозиторий клиента, синхронизируем пуши в обе стороны для ветки MASTER
  stage: sync
  image: alpine:latest
  before_script:
    - apk add --no-cache git
  script:
    - echo "Starting GitHub sync..."
    - git config --global user.name "GitLab Sync Bot"
    - git config --global user.email "gitlab-sync@example.com"
    - git remote add github https://$GITHUB_TOKEN@github.com/$GITHUB_REPO.git
    - echo "https://$GITHUB_TOKEN@github.com/$GITHUB_REPO.git"
    - git push github HEAD:$TARGET_BRANCH
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  tags:
    - dind